INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Singapore Singapore Orchard Road 323','Single','###',130,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Marina Bay Sands','Singapore Singapore Orchard RoadB 233','Single','###',80,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Yian Hotel','Singapore Singapore Orchard Road 56','Single','###',50,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Alex Hotel','Singapore Singapore Orchard Road 16','Single','###',50,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('RIki Hotel','Singapore Singapore Orchard Road 28','Single','###',75,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Winskey Hotel','Singapore Singapore Orchard Road 99','Single','###',45,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Winston Hotel','Singapore Singapore Orchard Road 78','Single','###',78,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('MaMa Hotel','Singapore Singapore Orchard Road 34','Single','###',70,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Flying Dutch Hotel','Singapore Singapore Orchard Road 28','Single','###',50,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('NorthWest Hotel','Singapore Singapore Orchard Road 39','Single','###',50,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Town Business Hotel','Singapore Singapore Maxwell Road 77','Single','###',75,99)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Boss Hotel','Singapore Singapore Maxwell Road 78','Single','###',45,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Miles Away Hotel','Singapore Singapore Maxwell Road 24','Single','###',78,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Kidding Hotel','Singapore Singapore Maxwell Road 109','Single','###',70,275)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('R Hotel','Singapore Singapore Maxwell Road 33','Single','###',50,275)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('SIngSing Hotel','Singapore Singapore Maxwell Road 457','Single','###',50,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Bali Hotel','Singapore Singapore Maxwell Road 300','Single','###',75,99)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Heaven Hotel','Singapore Singapore Maxwell Road 70','Single','###',45,275)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Home Hotel','Singapore Singapore Maxwell Road 1','Single','###',78,99)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('NUS Hotel','Singapore Singapore KentRidge Road 21','Single','###',70,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Beijing WangFujing Street 378','Single','###',50,90)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('WangFuJing Hotel','China Beijing WangFujing Street 423','Single','###',50,160)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Qitian Hotel','China Beijing WangFujing Street 243','Single','###',75,160)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('FuGuo Hotel','China Beijing WangFujing Street 520','Single','###',45,250)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Guo BingHotel','China Beijing Zhongshan Road 129','Single','###',78,250)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Beijing Changan Road 56','Single','###',70,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('HaiDu Hotel','China Beijing Changan Road 79','Single','###',50,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('DuHui Hotel','China Beijing Changan Road 32','Single','###',50,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('JingDu Hotel','China Beijing Changan Road 1','Single','###',75,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TianDi Hotel','China Beijing Changan Road 33','Single','###',45,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('ShangHai Hotel','China Shanghai Xujiahui Street 99','Single','###',78,99)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('DongHai Hotel','China Shanghai Xujiahui Street 59','Single','###',70,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Shanghai Xujiahui Street 45','Single','###',50,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('HaiYang Hotel','China Shanghai Xujiahui Street 83','Single','###',50,275)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TianDi Hotel','China Shanghai Xujiahui Street 79','Single','###',75,275)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('XinTianDi Hotel','China Shanghai Zhongshan Road 2','Single','###',45,176)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('MeiLing Hotel','China Shanghai Zhongshan Road 7','Single','###',78,99)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Memory Hotel','China Shanghai Zhongshan Road 45','Single','###',70,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Emma Hotel','China Shanghai Zhongshan Road 67','Single','###',50,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('QingQing Hotel','China Shanghai Zhongshan Road 21','Single','###',50,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Queen Hotel','China HongKong Granville Road 54','Single','###',75,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Elizabeth Hotel','China HongKong Granville Road 79','Single','###',45,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Thomas Hotel','China HongKong Granville Road 35','Single','###',78,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Grand Hotel','China HongKong Granville Road 68','Single','###',70,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China HongKong Granville Road 27','Single','###',50,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Peking Hotel','China HongKong Peking Road 172','Single','###',50,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shanghai Hotel','China HongKong Peking Road 46','Single','###',75,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Alice Hotel','China HongKong Peking Road 36','Single','###',45,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Empire Hotel','China HongKong Peking Road 39','Single','###',78,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Victor Hotel','China HongKong Peking Road 58','Single','###',70,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Macau Bay Sands','China Macau Estr. da Baia de Nossa  152','Single','###',50,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Golden Hotel','China Macau Estr. da Baia de Nossa  37','Single','###',50,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Nossa Hotel','China Macau Estr. da Baia de Nossa  69','Single','###',75,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Norman Hotel','China Macau Estr. da Baia de Nossa  55','Single','###',45,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Vigas Hotel','China Macau Estr. da Baia de Nossa  199','Single','###',78,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Huaqi Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 33','Single','###',70,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Senhora Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 47','Single','###',50,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 53','Single','###',50,300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Wings Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 98','Single','###',75,108)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Zing Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 57','Single','###',45,192)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Chou Hotel','China Taibei Zhongshan Road 45','Single','###',78,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TaiBeiDaJiuDian Hotel','China Taibei Zhongshan Road 9','Single','###',70,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('GuoBin Hotel','China Taibei Shilin Street 8','Single','###',50,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Wind Shangri-La Hotel','China Taibei Shilin Street 47','Single','###',50,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Floating Hotel','China Taibei Shilin Street 37','Single','###',75,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Zero Hotel','China Taibei Shilin Street 23','Single','###',45,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Blue Whale Hotel','China Taibei Shilin Street 111','Single','###',78,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Taibei 101 Hotel','China Taibei Section 5 Xinyi Street 123','Single','###',70,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Tracy Hotel','China Taibei Section 5 Xinyi Street 45','Single','###',50,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Titan Hotel','China Taibei Zhongzheng Road 87','Single','###',50,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Roma Hotel','China Taibei Zhongzheng Road 333','Single','###',75,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Para Hotel','Malaysia Kuala Lumpur Centre Street 61','Single','###',45,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fu Hotel','Malaysia Kuala Lumpur Centre Street 29','Single','###',78,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Kuala Hotel','Malaysia Kuala Lumpur Centre Street 41','Single','###',70,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Ming Hotel','Malaysia Kuala Lumpur Centre Street 37','Single','###',50,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Malaysia Kuala Lumpur Centre Street 77','Single','###',50,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Rolling Hotel','Malaysia Putrajaya Lebuh Bestari 32','Single','###',75,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Hyn Hotel','Malaysia Putrajaya Lebuh Bestari 67','Single','###',45,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fuji Hotel','Malaysia Putrajaya Lebuh Bestari 59','Single','###',78,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Sato Hotel','Malaysia Putrajaya Lebuh Bestari 75','Single','###',70,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Travel Business Hotel','Malaysia Putrajaya Lebuh Bestari 77','Single','###',50,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Australia Canberra Ainsile Ave 57','Single','###',50,208)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Lanka Hotel','Australia Canberra Ainsile Ave 89','Single','###',75,208)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Italy Hotel','Australia Canberra Ainsile Ave 17','Single','###',45,325)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('US Hotel','Australia Canberra Ainsile Ave 2','Single','###',78,325)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('King Hotel','Australia Canberra Ainsile Ave 85','Single','###',70,208)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Jack Hotel','Australia Sydney Centre Street 82','Single','###',50,117)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Australia Sydney Centre Street 66','Single','###',50,325)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Ace Hotel','Australia Sydney Johnson Street 97','Single','###',75,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Nature Hotel','Australia Sydney Johnson Street 63','Single','###',45,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Sea Hotel','Australia Sydney Johnson Street 61','Single','###',78,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Public Hotel','India New Deli Grandtsunk Road 84','Single','###',70,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Deli Hotel','India New Deli Grandtsunk Road 79','Single','###',50,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','India New Deli Grandtsunk Road 100','Single','###',50,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Friday Hotel','India New Deli Grandtsunk Road 10','Single','###',75,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('September Hotel','India New Deli Grandtsunk Road 19','Single','###',45,144)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Deli Hotel','India Mumbai Bhadran Nagar 22','Single','###',78,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','India Mumbai Bhadran Nagar 19','Single','###',70,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Me Hotel','India Mumbai Bhadran Nagar 56','Single','###',50,81)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fare Hotel','India Mumbai Bhadran Nagar 97','Single','###',50,625)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Singapore Singapore Orchard Road 323','Double','###',75,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Marina Bay Sands','Singapore Singapore Orchard Road 233','Double','###',45,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Yian Hotel','Singapore Singapore Orchard Road 56','Double','###',78,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Alex Hotel','Singapore Singapore Orchard Road 16','Double','###',70,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('RIki Hotel','Singapore Singapore Orchard Road 28','Double','###',50,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Winskey Hotel','Singapore Singapore Orchard Road 99','Double','###',50,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Winston Hotel','Singapore Singapore Orchard Road 78','Double','###',75,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('MaMa Hotel','Singapore Singapore Orchard Road 34','Double','###',45,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Flying Dutch Hotel','Singapore Singapore Orchard Road 28','Double','###',78,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('NorthWest Hotel','Singapore Singapore Orchard Road 39','Double','###',70,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Town Business Hotel','Singapore Singapore Maxwell Road 77','Double','###',50,247.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Boss Hotel','Singapore Singapore Maxwell Road 78','Double','###',50,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Miles Away Hotel','Singapore Singapore Maxwell Road 24','Double','###',75,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Kidding Hotel','Singapore Singapore Maxwell Road 109','Double','###',45,687.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('R Hotel','Singapore Singapore Maxwell Road 33','Double','###',78,687.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('SIngSing Hotel','Singapore Singapore Maxwell Road 457','Double','###',70,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Bali Hotel','Singapore Singapore Maxwell Road 300','Double','###',50,247.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Heaven Hotel','Singapore Singapore Maxwell Road 70','Double','###',50,687.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Home Hotel','Singapore Singapore Maxwell Road 1','Double','###',75,247.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('NUS Hotel','Singapore Singapore KentRidge Road 21','Double','###',45,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Beijing WangFujing Street 378','Double','###',78,225)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('WangFuJing Hotel','China Beijing WangFujing Street 423','Double','###',70,400)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Qitian Hotel','China Beijing WangFujing Street 243','Double','###',50,400)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('FuGuo Hotel','China Beijing WangFujing Street 520','Double','###',50,625)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Guo BingHotel','China Beijing Zhongshan Road 129','Double','###',75,625)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Beijing Changan Road 56','Double','###',45,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('HaiDu Hotel','China Beijing Changan Road 79','Double','###',78,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('DuHui Hotel','China Beijing Changan Road 32','Double','###',70,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('JingDu Hotel','China Beijing Changan Road 1','Double','###',50,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TianDi Hotel','China Beijing Changan Road 33','Double','###',50,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('ShangHai Hotel','China Shanghai Xujiahui Street 99','Double','###',75,247.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('DongHai Hotel','China Shanghai Xujiahui Street 59','Double','###',45,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Shanghai Xujiahui Street 45','Double','###',78,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('HaiYang Hotel','China Shanghai Xujiahui Street 83','Double','###',70,687.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TianDi Hotel','China Shanghai Xujiahui Street 79','Double','###',50,687.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('XinTianDi Hotel','China Shanghai Zhongshan Road 2','Double','###',50,440)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('MeiLing Hotel','China Shanghai Zhongshan Road 7','Double','###',75,247.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Memory Hotel','China Shanghai Zhongshan Road 45','Double','###',45,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Emma Hotel','China Shanghai Zhongshan Road 67','Double','###',78,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('QingQing Hotel','China Shanghai Zhongshan Road 21','Double','###',70,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Queen Hotel','China HongKong Granville Road 54','Double','###',50,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Elizabeth Hotel','China HongKong Granville Road 79','Double','###',50,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Thomas Hotel','China HongKong Granville Road 35','Double','###',75,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Grand Hotel','China HongKong Granville Road 68','Double','###',45,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China HongKong Granville Road 27','Double','###',78,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Peking Hotel','China HongKong Peking Road 172','Double','###',70,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shanghai Hotel','China HongKong Peking Road 46','Double','###',50,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Alice Hotel','China HongKong Peking Road 36','Double','###',50,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Empire Hotel','China HongKong Peking Road 39','Double','###',75,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Victor Hotel','China HongKong Peking Road 58','Double','###',45,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Macau Bay Sands','China Macau Estr. da Baia de Nossa  152','Double','###',78,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Golden Hotel','China Macau Estr. da Baia de Nossa  37','Double','###',70,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Nossa Hotel','China Macau Estr. da Baia de Nossa  69','Double','###',50,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Norman Hotel','China Macau Estr. da Baia de Nossa  55','Double','###',50,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Vigas Hotel','China Macau Estr. da Baia de Nossa  199','Double','###',75,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Huaqi Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 33','Double','###',45,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Senhora Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 47','Double','###',78,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 53','Double','###',70,750)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Wings Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 98','Double','###',50,270)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Zing Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 57','Double','###',50,480)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Chou Hotel','China Taibei Zhongshan Road 45','Double','###',75,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TaiBeiDaJiuDian Hotel','China Taibei Zhongshan Road 9','Double','###',45,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('GuoBin Hotel','China Taibei Shilin Street 8','Double','###',78,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Wind Shangri-La Hotel','China Taibei Shilin Street 47','Double','###',70,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Floating Hotel','China Taibei Shilin Street 37','Double','###',50,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Zero Hotel','China Taibei Shilin Street 23','Double','###',50,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Blue Whale Hotel','China Taibei Shilin Street 111','Double','###',75,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Taibei 101 Hotel','China Taibei Section 5 Xinyi Street 123','Double','###',45,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Tracy Hotel','China Taibei Section 5 Xinyi Street 45','Double','###',78,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Titan Hotel','China Taibei Zhongzheng Road 87','Double','###',70,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Roma Hotel','China Taibei Zhongzheng Road 333','Double','###',50,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Para Hotel','Malaysia Kuala Lumpur Centre Street 61','Double','###',50,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fu Hotel','Malaysia Kuala Lumpur Centre Street 29','Double','###',75,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Kuala Hotel','Malaysia Kuala Lumpur Centre Street 41','Double','###',45,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Ming Hotel','Malaysia Kuala Lumpur Centre Street 37','Double','###',78,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Malaysia Kuala Lumpur Centre Street 77','Double','###',70,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Rolling Hotel','Malaysia Putrajaya Lebuh Bestari 32','Double','###',50,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Hyn Hotel','Malaysia Putrajaya Lebuh Bestari 67','Double','###',50,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fuji Hotel','Malaysia Putrajaya Lebuh Bestari 59','Double','###',75,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Sato Hotel','Malaysia Putrajaya Lebuh Bestari 75','Double','###',45,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Travel Business Hotel','Malaysia Putrajaya Lebuh Bestari 77','Double','###',78,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Australia Canberra Ainsile Ave 57','Double','###',70,520)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Lanka Hotel','Australia Canberra Ainsile Ave 89','Double','###',50,520)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Italy Hotel','Australia Canberra Ainsile Ave 17','Double','###',50,812.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('US Hotel','Australia Canberra Ainsile Ave 2','Double','###',75,812.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('King Hotel','Australia Canberra Ainsile Ave 85','Double','###',45,520)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Jack Hotel','Australia Sydney Centre Street 82','Double','###',78,292.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Australia Sydney Centre Street 66','Double','###',70,812.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Ace Hotel','Australia Sydney Johnson Street 97','Double','###',50,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Nature Hotel','Australia Sydney Johnson Street 63','Double','###',50,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Sea Hotel','Australia Sydney Johnson Street 61','Double','###',75,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Public Hotel','India New Deli Grandtsunk Road 84','Double','###',45,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Deli Hotel','India New Deli Grandtsunk Road 79','Double','###',78,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','India New Deli Grandtsunk Road 100','Double','###',70,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Friday Hotel','India New Deli Grandtsunk Road 10','Double','###',50,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('September Hotel','India New Deli Grandtsunk Road 19','Double','###',50,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Deli Hotel','India Mumbai Bhadran Nagar 22','Double','###',75,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','India Mumbai Bhadran Nagar 19','Double','###',45,562.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Me Hotel','India Mumbai Bhadran Nagar 56','Double','###',78,202.5)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fare Hotel','India Mumbai Bhadran Nagar 97','Double','###',70,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Singapore Singapore Orchard Road 323','Trible','###',50,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Marina Bay Sands','Singapore Singapore Orchard Road 233','Trible','###',50,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Yian Hotel','Singapore Singapore Orchard Road 56','Trible','###',75,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Alex Hotel','Singapore Singapore Orchard Road 16','Trible','###',45,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('RIki Hotel','Singapore Singapore Orchard Road 28','Trible','###',78,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Winskey Hotel','Singapore Singapore Orchard Road 99','Trible','###',70,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Winston Hotel','Singapore Singapore Orchard Road 78','Trible','###',50,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('MaMa Hotel','Singapore Singapore Orchard Road 34','Trible','###',50,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Flying Dutch Hotel','Singapore Singapore Orchard Road 28','Trible','###',75,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('NorthWest Hotel','Singapore Singapore Orchard Road 39','Trible','###',45,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Town Business Hotel','Singapore Singapore Maxwell Road 77','Trible','###',78,396)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Boss Hotel','Singapore Singapore Maxwell Road 78','Trible','###',70,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Miles Away Hotel','Singapore Singapore Maxwell Road 24','Trible','###',50,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Kidding Hotel','Singapore Singapore Maxwell Road 109','Trible','###',50,1100)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('R Hotel','Singapore Singapore Maxwell Road 33','Trible','###',75,1100)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('SIngSing Hotel','Singapore Singapore Maxwell Road 457','Trible','###',45,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Bali Hotel','Singapore Singapore Maxwell Road 300','Trible','###',78,396)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Heaven Hotel','Singapore Singapore Maxwell Road 70','Trible','###',70,1100)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Home Hotel','Singapore Singapore Maxwell Road 1','Trible','###',50,396)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('NUS Hotel','Singapore Singapore KentRidge Road 21','Trible','###',50,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Beijing WangFujing Street 378','Trible','###',75,360)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('WangFuJing Hotel','China Beijing WangFujing Street 423','Trible','###',45,640)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Qitian Hotel','China Beijing WangFujing Street 243','Trible','###',78,640)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('FuGuo Hotel','China Beijing WangFujing Street 520','Trible','###',70,1000)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Guo BingHotel','China Beijing Zhongshan Road 129','Trible','###',50,1000)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Beijing Changan Road 56','Trible','###',50,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('HaiDu Hotel','China Beijing Changan Road 79','Trible','###',75,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('DuHui Hotel','China Beijing Changan Road 32','Trible','###',45,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('JingDu Hotel','China Beijing Changan Road 1','Trible','###',78,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TianDi Hotel','China Beijing Changan Road 33','Trible','###',70,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('ShangHai Hotel','China Shanghai Xujiahui Street 99','Trible','###',50,396)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('DongHai Hotel','China Shanghai Xujiahui Street 59','Trible','###',50,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Shanghai Xujiahui Street 45','Trible','###',75,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('HaiYang Hotel','China Shanghai Xujiahui Street 83','Trible','###',45,1100)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TianDi Hotel','China Shanghai Xujiahui Street 79','Trible','###',78,1100)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('XinTianDi Hotel','China Shanghai Zhongshan Road 2','Trible','###',70,704)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('MeiLing Hotel','China Shanghai Zhongshan Road 7','Trible','###',50,396)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Memory Hotel','China Shanghai Zhongshan Road 45','Trible','###',50,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Emma Hotel','China Shanghai Zhongshan Road 67','Trible','###',75,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('QingQing Hotel','China Shanghai Zhongshan Road 21','Trible','###',45,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Queen Hotel','China HongKong Granville Road 54','Trible','###',78,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Elizabeth Hotel','China HongKong Granville Road 79','Trible','###',70,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Thomas Hotel','China HongKong Granville Road 35','Trible','###',50,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Grand Hotel','China HongKong Granville Road 68','Trible','###',50,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China HongKong Granville Road 27','Trible','###',75,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Peking Hotel','China HongKong Peking Road 172','Trible','###',45,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shanghai Hotel','China HongKong Peking Road 46','Trible','###',78,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Alice Hotel','China HongKong Peking Road 36','Trible','###',70,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Empire Hotel','China HongKong Peking Road 39','Trible','###',50,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Victor Hotel','China HongKong Peking Road 58','Trible','###',50,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Macau Bay Sands','China Macau Estr. da Baia de Nossa  152','Trible','###',75,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Golden Hotel','China Macau Estr. da Baia de Nossa  37','Trible','###',45,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Nossa Hotel','China Macau Estr. da Baia de Nossa  69','Trible','###',78,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Norman Hotel','China Macau Estr. da Baia de Nossa  55','Trible','###',70,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Vigas Hotel','China Macau Estr. da Baia de Nossa  199','Trible','###',50,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Huaqi Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 33','Trible','###',50,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Senhora Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 47','Trible','###',75,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 53','Trible','###',45,1200)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Wings Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 98','Trible','###',78,432)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Zing Hotel','China Macau Estrada da Baia de Nossa Senhora da Esperanca 57','Trible','###',70,768)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Chou Hotel','China Taibei Zhongshan Road 45','Trible','###',50,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('TaiBeiDaJiuDian Hotel','China Taibei Zhongshan Road 9','Trible','###',50,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('GuoBin Hotel','China Taibei Shilin Street 8','Trible','###',75,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Wind Shangri-La Hotel','China Taibei Shilin Street 47','Trible','###',45,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Floating Hotel','China Taibei Shilin Street 37','Trible','###',78,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Zero Hotel','China Taibei Shilin Street 23','Trible','###',70,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Blue Whale Hotel','China Taibei Shilin Street 111','Trible','###',50,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Taibei 101 Hotel','China Taibei Section 5 Xinyi Street 123','Trible','###',50,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Tracy Hotel','China Taibei Section 5 Xinyi Street 45','Trible','###',75,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Titan Hotel','China Taibei Zhongzheng Road 87','Trible','###',45,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Roma Hotel','China Taibei Zhongzheng Road 333','Trible','###',78,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Para Hotel','Malaysia Kuala Lumpur Centre Street 61','Trible','###',70,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fu Hotel','Malaysia Kuala Lumpur Centre Street 29','Trible','###',50,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Kuala Hotel','Malaysia Kuala Lumpur Centre Street 41','Trible','###',50,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Ming Hotel','Malaysia Kuala Lumpur Centre Street 37','Trible','###',75,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Malaysia Kuala Lumpur Centre Street 77','Trible','###',45,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Rolling Hotel','Malaysia Putrajaya Lebuh Bestari 32','Trible','###',78,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Hyn Hotel','Malaysia Putrajaya Lebuh Bestari 67','Trible','###',70,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fuji Hotel','Malaysia Putrajaya Lebuh Bestari 59','Trible','###',50,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Sato Hotel','Malaysia Putrajaya Lebuh Bestari 75','Trible','###',50,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Travel Business Hotel','Malaysia Putrajaya Lebuh Bestari 77','Trible','###',75,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Australia Canberra Ainsile Ave 57','Trible','###',45,832)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Lanka Hotel','Australia Canberra Ainsile Ave 89','Trible','###',78,832)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Italy Hotel','Australia Canberra Ainsile Ave 17','Trible','###',70,1300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('US Hotel','Australia Canberra Ainsile Ave 2','Trible','###',50,1300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('King Hotel','Australia Canberra Ainsile Ave 85','Trible','###',50,832)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Jack Hotel','Australia Sydney Centre Street 82','Trible','###',75,468)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','Australia Sydney Centre Street 66','Trible','###',45,1300)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Ace Hotel','Australia Sydney Johnson Street 97','Trible','###',78,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Nature Hotel','Australia Sydney Johnson Street 63','Trible','###',70,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Sea Hotel','Australia Sydney Johnson Street 61','Trible','###',50,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Public Hotel','India New Deli Grandtsunk Road 84','Trible','###',50,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Deli Hotel','India New Deli Grandtsunk Road 79','Trible','###',75,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','India New Deli Grandtsunk Road 100','Trible','###',45,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Friday Hotel','India New Deli Grandtsunk Road 10','Trible','###',78,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('September Hotel','India New Deli Grandtsunk Road 19','Trible','###',70,576)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Deli Hotel','India Mumbai Bhadran Nagar 22','Trible','###',50,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Shangri-La Hotel','India Mumbai Bhadran Nagar 19','Trible','###',50,900)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Me Hotel','India Mumbai Bhadran Nagar 56','Trible','###',75,324)
INSERT INTO RoomType(hotel_name,hotel_address,room_type,room_date,quantity,price) VALUES ('Fare Hotel','India Mumbai Bhadran Nagar 97','Trible','###',45,576)
